// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH7xHeeDN_kYpl3aIuVCSOGiZ737e94Q8',
    appId: '1:77257738641:web:0f67cb410003478ad47230',
    messagingSenderId: '77257738641',
    projectId: 'watercat-ea665',
    authDomain: 'watercat-ea665.firebaseapp.com',
    databaseURL: 'https://watercat-ea665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watercat-ea665.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXucbAbfvLJdnldFcwY7CRWlzSkHTTfjY',
    appId: '1:77257738641:android:f249294bc2d40b3dd47230',
    messagingSenderId: '77257738641',
    projectId: 'watercat-ea665',
    databaseURL: 'https://watercat-ea665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watercat-ea665.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIXZfs1ips9xEztsSy4I6WAnjlVnNiCI',
    appId: '1:77257738641:ios:4a9f6ad0fb12f568d47230',
    messagingSenderId: '77257738641',
    projectId: 'watercat-ea665',
    databaseURL: 'https://watercat-ea665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watercat-ea665.appspot.com',
    iosBundleId: 'com.example.cwrdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeIXZfs1ips9xEztsSy4I6WAnjlVnNiCI',
    appId: '1:77257738641:ios:51b305cdbac843b7d47230',
    messagingSenderId: '77257738641',
    projectId: 'watercat-ea665',
    databaseURL: 'https://watercat-ea665-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watercat-ea665.appspot.com',
    iosBundleId: 'com.example.cwrdm.RunnerTests',
  );
}
