// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1qOhmdsFxwRxAMH0KHIroW1yN5eOD9Ec',
    appId: '1:171516733719:web:3589dddb23ad3298722f52',
    messagingSenderId: '171516733719',
    projectId: 'cwrdm-9bb46',
    authDomain: 'cwrdm-9bb46.firebaseapp.com',
    databaseURL: 'https://cwrdm-9bb46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cwrdm-9bb46.appspot.com',
    measurementId: 'G-L0EPMQ4JDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALb0_UKX57EqicAKf_HMXTCLlm426Cq-o',
    appId: '1:171516733719:android:fced15594799f1b4722f52',
    messagingSenderId: '171516733719',
    projectId: 'cwrdm-9bb46',
    databaseURL: 'https://cwrdm-9bb46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cwrdm-9bb46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19eKqjpcpsuCNCx_nqr9MYpck_xVNgIg',
    appId: '1:171516733719:ios:7a6269f2890a5cfb722f52',
    messagingSenderId: '171516733719',
    projectId: 'cwrdm-9bb46',
    databaseURL: 'https://cwrdm-9bb46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cwrdm-9bb46.appspot.com',
    iosBundleId: 'com.example.cwrdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19eKqjpcpsuCNCx_nqr9MYpck_xVNgIg',
    appId: '1:171516733719:ios:00f3633ba0b1bad1722f52',
    messagingSenderId: '171516733719',
    projectId: 'cwrdm-9bb46',
    databaseURL: 'https://cwrdm-9bb46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cwrdm-9bb46.appspot.com',
    iosBundleId: 'com.example.cwrdm.RunnerTests',
  );
}
